version: 2.1

jobs:
  dapp_test:
    docker:
      - image: bakii0499/dapptools:0.48.1-solc-0.8.7-beta
    resource_class: medium
    steps:
      - run:
          name: Checkout liquidations
          command: |
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:maple-labs/liquidations.git .
            git checkout $CIRCLE_BRANCH
      - run:
          name: Build and test contracts
          command: |
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git submodule update --init --recursive
            ./test.sh -c ./config/ci.json
          no_output_timeout: 60m
workflows:
  version: 2
  test_all:
    jobs:
      - dapp_test:
          context: seth
