name: liquidations
version: 1.0.0
source: contracts
packages:
  - path: contracts/Liquidator.sol
    contractName: Liquidator
  - path: contracts/SushiswapStrategy.sol
    contractName: SushiswapStrategy
  - path: contracts/UniswapV2Strategy.sol
    contractName: UniswapV2Strategy
customDescription: Maple Liquidations Artifacts and ABIs
